// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name      string `json:"name"`
	PassWorld string `json:"passWorld"`
}

type LoginResponse struct {
	Id    uint   `json:"id"`
	Name  string `json:"name"`
	Token string `json:"token"`
}
